spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:wallet;DB_CLOSE_DELAY=1000
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect